# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14sample_service.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x18\n\x07Request\x12\r\n\x05input\x18\x01 \x01(\t\"\x1a\n\x08Response\x12\x0e\n\x06output\x18\x01 \x01(\t\"\xef\x01\n\x16SpecialDataTypeRequest\x12(\n\x04\x64\x61te\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05names\x18\x02 \x03(\t\x12G\n\x10name2phoneNumMap\x18\x03 \x03(\x0b\x32-.SpecialDataTypeRequest.Name2phoneNumMapEntry\x12\x1a\n\x12numberOfCreditCard\x18\x04 \x01(\x05\x1a\x37\n\x15Name2phoneNumMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xf1\x01\n\x17SpecialDataTypeResponse\x12(\n\x04\x64\x61te\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05names\x18\x02 \x03(\t\x12H\n\x10name2phoneNumMap\x18\x03 \x03(\x0b\x32..SpecialDataTypeResponse.Name2phoneNumMapEntry\x12\x1a\n\x12numberOfCreditCard\x18\x04 \x01(\x05\x1a\x37\n\x15Name2phoneNumMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\x89\x02\n\rSampleService\x12!\n\x08\x64oSimple\x12\x08.Request\x1a\t.Response\"\x00\x12.\n\x13\x64oResponseStreaming\x12\x08.Request\x1a\t.Response\"\x00\x30\x01\x12-\n\x12\x64oRequestStreaming\x12\x08.Request\x1a\t.Response\"\x00(\x01\x12,\n\x0f\x64oBidirectional\x12\x08.Request\x1a\t.Response\"\x00(\x01\x30\x01\x12H\n\x11\x64oSpecialDataType\x12\x17.SpecialDataTypeRequest\x1a\x18.SpecialDataTypeResponse\"\x00\x62\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
_SPECIALDATATYPEREQUEST = DESCRIPTOR.message_types_by_name['SpecialDataTypeRequest']
_SPECIALDATATYPEREQUEST_NAME2PHONENUMMAPENTRY = _SPECIALDATATYPEREQUEST.nested_types_by_name['Name2phoneNumMapEntry']
_SPECIALDATATYPERESPONSE = DESCRIPTOR.message_types_by_name['SpecialDataTypeResponse']
_SPECIALDATATYPERESPONSE_NAME2PHONENUMMAPENTRY = _SPECIALDATATYPERESPONSE.nested_types_by_name['Name2phoneNumMapEntry']
Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'sample_service_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'sample_service_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)

SpecialDataTypeRequest = _reflection.GeneratedProtocolMessageType('SpecialDataTypeRequest', (_message.Message,), {

  'Name2phoneNumMapEntry' : _reflection.GeneratedProtocolMessageType('Name2phoneNumMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _SPECIALDATATYPEREQUEST_NAME2PHONENUMMAPENTRY,
    '__module__' : 'sample_service_pb2'
    # @@protoc_insertion_point(class_scope:SpecialDataTypeRequest.Name2phoneNumMapEntry)
    })
  ,
  'DESCRIPTOR' : _SPECIALDATATYPEREQUEST,
  '__module__' : 'sample_service_pb2'
  # @@protoc_insertion_point(class_scope:SpecialDataTypeRequest)
  })
_sym_db.RegisterMessage(SpecialDataTypeRequest)
_sym_db.RegisterMessage(SpecialDataTypeRequest.Name2phoneNumMapEntry)

SpecialDataTypeResponse = _reflection.GeneratedProtocolMessageType('SpecialDataTypeResponse', (_message.Message,), {

  'Name2phoneNumMapEntry' : _reflection.GeneratedProtocolMessageType('Name2phoneNumMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _SPECIALDATATYPERESPONSE_NAME2PHONENUMMAPENTRY,
    '__module__' : 'sample_service_pb2'
    # @@protoc_insertion_point(class_scope:SpecialDataTypeResponse.Name2phoneNumMapEntry)
    })
  ,
  'DESCRIPTOR' : _SPECIALDATATYPERESPONSE,
  '__module__' : 'sample_service_pb2'
  # @@protoc_insertion_point(class_scope:SpecialDataTypeResponse)
  })
_sym_db.RegisterMessage(SpecialDataTypeResponse)
_sym_db.RegisterMessage(SpecialDataTypeResponse.Name2phoneNumMapEntry)

_SAMPLESERVICE = DESCRIPTOR.services_by_name['SampleService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SPECIALDATATYPEREQUEST_NAME2PHONENUMMAPENTRY._options = None
  _SPECIALDATATYPEREQUEST_NAME2PHONENUMMAPENTRY._serialized_options = b'8\001'
  _SPECIALDATATYPERESPONSE_NAME2PHONENUMMAPENTRY._options = None
  _SPECIALDATATYPERESPONSE_NAME2PHONENUMMAPENTRY._serialized_options = b'8\001'
  _REQUEST._serialized_start=57
  _REQUEST._serialized_end=81
  _RESPONSE._serialized_start=83
  _RESPONSE._serialized_end=109
  _SPECIALDATATYPEREQUEST._serialized_start=112
  _SPECIALDATATYPEREQUEST._serialized_end=351
  _SPECIALDATATYPEREQUEST_NAME2PHONENUMMAPENTRY._serialized_start=296
  _SPECIALDATATYPEREQUEST_NAME2PHONENUMMAPENTRY._serialized_end=351
  _SPECIALDATATYPERESPONSE._serialized_start=354
  _SPECIALDATATYPERESPONSE._serialized_end=595
  _SPECIALDATATYPERESPONSE_NAME2PHONENUMMAPENTRY._serialized_start=296
  _SPECIALDATATYPERESPONSE_NAME2PHONENUMMAPENTRY._serialized_end=351
  _SAMPLESERVICE._serialized_start=598
  _SAMPLESERVICE._serialized_end=863
# @@protoc_insertion_point(module_scope)
